// <auto-generated />
using System;
using FamilyTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTree.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820195740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FamilyTree.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("AnneId")
                        .HasColumnType("int");

                    b.Property<int?>("BabaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("OlumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AnneId");

                    b.HasIndex("BabaId");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("Ad", "Soyad");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FamilyTree.Models.PersonPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonPhotos");
                });

            modelBuilder.Entity("FamilyTree.Models.SpouseRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DivorceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("MarriageDate")
                        .HasColumnType("date");

                    b.Property<int>("Person1Id")
                        .HasColumnType("int");

                    b.Property<int>("Person2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Person2Id");

                    b.HasIndex("Person1Id", "Person2Id")
                        .IsUnique();

                    b.ToTable("SpouseRelationships");
                });

            modelBuilder.Entity("FamilyTree.Models.Person", b =>
                {
                    b.HasOne("FamilyTree.Models.Person", "Anne")
                        .WithMany("AnneCocuklari")
                        .HasForeignKey("AnneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyTree.Models.Person", "Baba")
                        .WithMany("BabaCocuklari")
                        .HasForeignKey("BabaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Anne");

                    b.Navigation("Baba");
                });

            modelBuilder.Entity("FamilyTree.Models.PersonPhoto", b =>
                {
                    b.HasOne("FamilyTree.Models.Person", "Person")
                        .WithMany("Photos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FamilyTree.Models.SpouseRelationship", b =>
                {
                    b.HasOne("FamilyTree.Models.Person", "Person1")
                        .WithMany("SpouseRelationshipsAsPerson1")
                        .HasForeignKey("Person1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyTree.Models.Person", "Person2")
                        .WithMany("SpouseRelationshipsAsPerson2")
                        .HasForeignKey("Person2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person1");

                    b.Navigation("Person2");
                });

            modelBuilder.Entity("FamilyTree.Models.Person", b =>
                {
                    b.Navigation("AnneCocuklari");

                    b.Navigation("BabaCocuklari");

                    b.Navigation("Photos");

                    b.Navigation("SpouseRelationshipsAsPerson1");

                    b.Navigation("SpouseRelationshipsAsPerson2");
                });
#pragma warning restore 612, 618
        }
    }
}
